name = "action"
main = "worker.js"
compatibility_date = "2026-04-06"
account_id = "8058cf61f0cd44c4edd78080b193033a"

[[kv_namespaces]]
binding = "ACTION_DATA"
id = "73d752b833ee47f6886a37897063a0e6"

[[r2_buckets]]
binding = "act-image"
bucket_name = "humanaction"
